 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Nov/2016 18:59:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2016 18:59:00] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [09/Nov/2016 18:59:00] "GET /static/doodlemeetimage4.jpg HTTP/1.1" 304 -
[2016-11-09 18:59:00,784] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 91, in handler
    text = text_dict[name]
KeyError: u'favicon.ico'
127.0.0.1 - - [09/Nov/2016 18:59:00] "GET /favicon.ico HTTP/1.1" 500 -
127.0.0.1 - - [09/Nov/2016 18:59:05] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [09/Nov/2016 18:59:05] "GET /show_entries HTTP/1.1" 200 -
[2016-11-09 18:59:05,458] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 91, in handler
    text = text_dict[name]
KeyError: u'favicon.ico'
127.0.0.1 - - [09/Nov/2016 18:59:05] "GET /favicon.ico HTTP/1.1" 500 -
127.0.0.1 - - [09/Nov/2016 18:59:07] "GET /fishing HTTP/1.1" 200 -
[2016-11-09 18:59:08,309] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 91, in handler
    text = text_dict[name]
KeyError: u'favicon.ico'
127.0.0.1 - - [09/Nov/2016 18:59:08] "GET /favicon.ico HTTP/1.1" 500 -
127.0.0.1 - - [09/Nov/2016 18:59:10] "GET /getloc/sea%20fishing HTTP/1.1" 200 -
[2016-11-09 18:59:10,596] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 91, in handler
    text = text_dict[name]
KeyError: u'favicon.ico'
127.0.0.1 - - [09/Nov/2016 18:59:10] "GET /favicon.ico HTTP/1.1" 500 -
127.0.0.1 - - [09/Nov/2016 18:59:12] "GET /show_entries HTTP/1.1" 200 -
[2016-11-09 18:59:17,932] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 91, in handler
    text = text_dict[name]
KeyError: u'favicon.ico'
127.0.0.1 - - [09/Nov/2016 18:59:17] "GET /favicon.ico HTTP/1.1" 500 -
127.0.0.1 - - [09/Nov/2016 18:59:19] "GET /interests HTTP/1.1" 200 -
[2016-11-09 18:59:28,522] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 91, in handler
    text = text_dict[name]
KeyError: u'favicon.ico'
127.0.0.1 - - [09/Nov/2016 18:59:28] "GET /favicon.ico HTTP/1.1" 500 -
running on 0.0.0.0:8080
logged in DHruv
logged in DHruv
('logged in : ', True)
******************I am in loc_display *********************************
('activity_category', u'fishing')
[(1, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'New York', u'Brooklyn', u'Captain Dave'), (2, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'Galveston', u'Texas', u'Galveston Bay'), (3, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'San Diego', u'California', u'California coast'), (4, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'Montauk', u'New York', u' Long Island Sound'), (5, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'MIAMI', u'Florida', u'Atlantic Coast')]
('logged in : ', True)
[(u'Museum of Modern Arts', u'New York', u'New York', datetime.time(10, 0), datetime.time(17, 0)), (u'Museum of Modern Arts', u'New York', u'New York', datetime.time(10, 0), datetime.time(17, 0)), (u'Museum of Modern Arts', u'New York', u'New York', datetime.time(10, 0), datetime.time(17, 0))]
[(1, 4, 1, datetime.time(10, 0), datetime.time(17, 0), u'New York', u'New York', u'Museum of Modern Arts'), (2, 4, 1, datetime.time(9, 0), datetime.time(18, 0), u'Boston', u'massachusetts', u'The Institute of Temporary Art'), (1, 4, 2, datetime.time(9, 0), datetime.time(18, 0), u'New York', u'New York', u'Metropolitan Museum'), (2, 4, 2, datetime.time(9, 0), datetime.time(18, 0), u'Boston', u'massachusetts', u'Boston Museum of Fine Arts'), (1, 4, 3, datetime.time(10, 0), datetime.time(17, 0), u'New York', u'New York', u'Natural History Museum'), (1, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'New York', u'Brooklyn', u'Captain Dave'), (2, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'Galveston', u'Texas', u'Galveston Bay'), (3, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'San Diego', u'California', u'California coast'), (4, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'Montauk', u'New York', u' Long Island Sound'), (5, 7, 2, datetime.time(10, 0), datetime.time(17, 0), u'MIAMI', u'Florida', u'Atlantic Coast')]
[(1, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 12, 0), 30), (2, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 12, 0), 20), (3, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 12, 0), 40), (4, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 12, 0), 40), (5, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 12, 0), 40), (6, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 13, 0), 40), (7, 7, 2, 1, datetime.datetime(2016, 12, 15, 10, 0), datetime.datetime(2016, 12, 15, 12, 0), 40), (3, 7, 2, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 12, 0), 40), (3, 7, 2, 1, datetime.datetime(2016, 12, 15, 10, 0), datetime.datetime(2016, 12, 15, 12, 0), 35), (2, 7, 2, 1, datetime.datetime(2016, 12, 15, 10, 0), datetime.datetime(2016, 12, 15, 12, 0), 120), (1, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 13), datetime.datetime(2016, 10, 15, 11, 24), 1000), (1, 4, 1, 1, datetime.datetime(2016, 11, 15, 10, 0), datetime.datetime(2016, 11, 15, 11, 0), 1000)]
